// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Suppliers documents */
interface SuppliersDocumentData {
    /**
     * Name field in *Suppliers*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: suppliers.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.RichTextField;
    /**
     * Slice Zone field in *Suppliers*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: suppliers.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<SuppliersDocumentDataSlicesSlice>;
}
/**
 * Slice for *Suppliers → Slice Zone*
 *
 */
type SuppliersDocumentDataSlicesSlice = SupplierCardSlice;
/**
 * Suppliers document from Prismic
 *
 * - **API ID**: `suppliers`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SuppliersDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<SuppliersDocumentData>, "suppliers", Lang>;
export type AllDocumentTypes = SuppliersDocument;
/**
 * Primary content in SupplierCard → Primary
 *
 */
interface SupplierCardSliceDefaultPrimary {
    /**
     * Title field in *SupplierCard → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: supplier_card.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Tagline field in *SupplierCard → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: supplier_card.primary.tagline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    tagline: prismicT.RichTextField;
    /**
     * Image field in *SupplierCard → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: supplier_card.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    image: prismicT.LinkToMediaField;
    /**
     * Rating field in *SupplierCard → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: supplier_card.primary.rating
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    rating: prismicT.NumberField;
}
/**
 * Default variation for SupplierCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SupplierCard`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SupplierCardSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SupplierCardSliceDefaultPrimary>, never>;
/**
 * Slice variation for *SupplierCard*
 *
 */
type SupplierCardSliceVariation = SupplierCardSliceDefault;
/**
 * SupplierCard Shared Slice
 *
 * - **API ID**: `supplier_card`
 * - **Description**: `SupplierCard`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SupplierCardSlice = prismicT.SharedSlice<"supplier_card", SupplierCardSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { SuppliersDocumentData, SuppliersDocumentDataSlicesSlice, SuppliersDocument, AllDocumentTypes, SupplierCardSliceDefaultPrimary, SupplierCardSliceDefault, SupplierCardSliceVariation, SupplierCardSlice };
    }
}
